# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 126bcdace964553781ea9b21a6a69dafc3bc04d9f7111ad8352741c8d4ac81cfd47c5a745912a964e914b8832875db0c20f6e840a59d7773233506bd4889ab79

test:
  secret_key_base: f11018a021a2d455c5540e300aa1e7e5181470a16c9035395a8930aae2123175f99a3ec8ce479a566c306b8b2a4a6f78ecaa8948f7a10790092dd24e0671c1e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
